//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emily.Clock
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Emily.Clock.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static nanoFramework.UI.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static nanoFramework.UI.Font GetFont(Resources.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            Alarm_22 = -32373,
            Lightbulb_22 = -30712,
            Wireless_48 = -29634,
            Close_22 = -21248,
            Check_22 = -13079,
            Settings_22 = -9591,
            Warning_48 = -4605,
            Restart_22 = -233,
            Lightbulb_22_Outline = 5943,
            Palette_22 = 13115,
            Loading_48 = 14590,
            Alarm_22_Outline = 24756,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Inter_Medium_72 = 11746,
            Inter_Medium_20 = 15457,
            Inter_Medium_14 = 22059,
            Inter_Medium_16 = 22061,
            Consolas_Regular_10 = 22208,
        }
    }
}
